package com.mahindra.be_lms.model;

import android.os.Parcel;
import android.os.Parcelable;

import com.google.gson.annotations.SerializedName;
import com.mahindra.be_lms.model.*;

import java.util.List;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END

import android.os.Parcel;
import android.os.Parcelable;

import com.google.gson.annotations.SerializedName;

import java.util.List;

/**
 * Entity mapped to table "EVENT".
 */
public class Event implements Parcelable {

    public static final Creator<Event> CREATOR = new Creator<Event>() {
        @Override
        public Event createFromParcel(Parcel source) {
            return new Event(source);
        }

        @Override
        public Event[] newArray(int size) {
            return new Event[size];
        }
    };
    @SerializedName("none")
    private Long id;
    @SerializedName("id")
    private String eventID;
    @SerializedName("name")
    private String eventName;
    @SerializedName("description")
    private String eventDescription;

    @SerializedName("Month")
    private String eventMonth;
    @SerializedName("timestart")
    private String eventFromdate;
    @SerializedName("Todate")
    private String eventTodate;
    @SerializedName("is_nominated")
    private String eventNomination;
    @SerializedName("Venue")
    private String eventVenue;
    @SerializedName("program_no")
    private String eventProgram_no;
    @SerializedName("courses")
    private List<com.mahindra.be_lms.db.Course> courseList;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END


    public Event() {
    }

    public Event(Long id) {
        this.id = id;
    }

    public Event(Long id, String eventID, String eventName, String eventMonth, String eventFromdate, String eventTodate, String eventNomination, String eventVenue, String eventProgram_no,String eventDescription) {
        this.id = id;
        this.eventID = eventID;
        this.eventName = eventName;
        this.eventMonth = eventMonth;
        this.eventFromdate = eventFromdate;
        this.eventTodate = eventTodate;
        this.eventNomination = eventNomination;
        this.eventVenue = eventVenue;
        this.eventProgram_no = eventProgram_no;
        this.eventDescription = eventDescription;
    }

    protected Event(Parcel in) {
        this.id = (Long) in.readValue(Long.class.getClassLoader());
        this.eventID = in.readString();
        this.eventName = in.readString();
        this.eventMonth = in.readString();
        this.eventFromdate = in.readString();
        this.eventTodate = in.readString();
        this.eventNomination = in.readString();
        this.eventVenue = in.readString();
        this.eventProgram_no = in.readString();
        this.courseList = in.createTypedArrayList(com.mahindra.be_lms.db.Course.CREATOR);

        this.eventDescription = in.readString();

    }

    public List<com.mahindra.be_lms.db.Course> getCourseList() {
        return courseList;
    }

    public void setCourseList(List<com.mahindra.be_lms.db.Course> courseList) {
        this.courseList = courseList;
    }






    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getEventID() {
        return eventID;
    }

    public void setEventID(String eventID) {
        this.eventID = eventID;
    }

    public String getEventName() {
        return eventName;
    }

    public void setEventName(String eventName) {
        this.eventName = eventName;
    }

    public String getEventMonth() {
        return eventMonth;
    }

    public void setEventMonth(String eventMonth) {
        this.eventMonth = eventMonth;
    }

    public String getEventFromdate() {
        return eventFromdate;
    }

    public void setEventFromdate(String eventFromdate) {
        this.eventFromdate = eventFromdate;
    }

    public String getEventTodate() {
        return eventTodate;
    }

    public void setEventTodate(String eventTodate) {
        this.eventTodate = eventTodate;
    }

    public String getEventDescription() {
        return eventDescription;
    }

    public void setEventDescription(String eventDescription) {
        this.eventDescription = eventDescription;
    }

    public String getEventNomination() {
        return eventNomination;
    }

    public void setEventNomination(String eventNomination) {
        this.eventNomination = eventNomination;
    }

    public String getEventVenue() {
        return eventVenue;
    }

    public void setEventVenue(String eventVenue) {
        this.eventVenue = eventVenue;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

    public String getEventProgram_no() {
        return eventProgram_no;
    }

    public void setEventProgram_no(String eventProgram_no) {
        this.eventProgram_no = eventProgram_no;
    }

    @Override
    public int describeContents() {
        return 0;
    }

    @Override
    public void writeToParcel(Parcel dest, int flags) {
        dest.writeValue(this.id);
        dest.writeString(this.eventID);
        dest.writeString(this.eventName);
        dest.writeString(this.eventMonth);
        dest.writeString(this.eventFromdate);
        dest.writeString(this.eventTodate);
        dest.writeString(this.eventNomination);
        dest.writeString(this.eventVenue);
        dest.writeString(this.eventDescription);
        dest.writeString(this.eventProgram_no);
        dest.writeTypedList(this.courseList);


    }
}
