package com.mahindra.be_lms.db;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END

import android.os.Parcel;
import android.os.Parcelable;

import com.google.gson.annotations.SerializedName;

/**
 * Entity mapped to table "CATEGORY".
 */
public class Category implements Parcelable {
    public static final Creator<Category> CREATOR = new Creator<Category>() {
        @Override
        public Category createFromParcel(Parcel source) {
            return new Category(source);
        }

        @Override
        public Category[] newArray(int size) {
            return new Category[size];
        }
    };
    @SerializedName("none")
    private Long id;
    @SerializedName("id")
    private String categoryID;
    @SerializedName("name")
    private String categoryName;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END
    @SerializedName("sequence")
    private String categorySequence;

    public Category() {
    }

    public Category(Long id) {
        this.id = id;
    }

    public Category(Long id, String categoryID, String categoryName, String categorySequence) {
        this.id = id;
        this.categoryID = categoryID;
        this.categoryName = categoryName;
        this.categorySequence = categorySequence;
    }

    public Category(String categoryID, String categoryName, String categorySequence) {
        this.categoryID = categoryID;
        this.categoryName = categoryName;
        this.categorySequence = categorySequence;
    }

    protected Category(Parcel in) {
        this.id = (Long) in.readValue(Long.class.getClassLoader());
        this.categoryID = in.readString();
        this.categoryName = in.readString();
        this.categorySequence = in.readString();
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getCategoryID() {
        return categoryID;
    }

    public void setCategoryID(String categoryID) {
        this.categoryID = categoryID;
    }

    public String getCategoryName() {
        return categoryName;
    }

    public void setCategoryName(String categoryName) {
        this.categoryName = categoryName;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

    public String getCategorySequence() {
        return categorySequence;
    }

    public void setCategorySequence(String categorySequence) {
        this.categorySequence = categorySequence;
    }

    @Override
    public int describeContents() {
        return 0;
    }

    @Override
    public void writeToParcel(Parcel dest, int flags) {
        dest.writeValue(this.id);
        dest.writeString(this.categoryID);
        dest.writeString(this.categoryName);
        dest.writeString(this.categorySequence);
    }

    @Override
    public String toString() {
        return categoryName;
    }
}
