package com.mahindra.be_lms.db;

import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.DaoConfig;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * DAO for table "COORDINATORS".
 */
public class CoordinatorsDao extends AbstractDao<Coordinators, Long> {

    public static final String TABLENAME = "COORDINATORS";

    public CoordinatorsDao(DaoConfig config) {
        super(config);
    }


    public CoordinatorsDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /**
     * Creates the underlying database table.
     */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists ? "IF NOT EXISTS " : "";
        db.execSQL("CREATE TABLE " + constraint + "\"COORDINATORS\" (" + //
                "\"_id\" INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: id
                "\"COORDINATORS_ID\" TEXT," + // 1: coordinatorsID
                "\"COORDINATORS_NAME\" TEXT);"); // 2: coordinatorsName
    }

    /**
     * Drops the underlying database table.
     */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"COORDINATORS\"";
        db.execSQL(sql);
    }

    /**
     * @inheritdoc
     */
    @Override
    protected void bindValues(SQLiteStatement stmt, Coordinators entity) {
        stmt.clearBindings();

        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }

        String coordinatorsID = entity.getCoordinatorsID();
        if (coordinatorsID != null) {
            stmt.bindString(2, coordinatorsID);
        }

        String coordinatorsName = entity.getCoordinatorsName();
        if (coordinatorsName != null) {
            stmt.bindString(3, coordinatorsName);
        }
    }

    /**
     * @inheritdoc
     */
    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }

    /**
     * @inheritdoc
     */
    @Override
    public Coordinators readEntity(Cursor cursor, int offset) {
        Coordinators entity = new Coordinators( //
                cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
                cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // coordinatorsID
                cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2) // coordinatorsName
        );
        return entity;
    }

    /**
     * @inheritdoc
     */
    @Override
    public void readEntity(Cursor cursor, Coordinators entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setCoordinatorsID(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setCoordinatorsName(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
    }

    /**
     * @inheritdoc
     */
    @Override
    protected Long updateKeyAfterInsert(Coordinators entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }

    /**
     * @inheritdoc
     */
    @Override
    public Long getKey(Coordinators entity) {
        if (entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    /**
     * @inheritdoc
     */
    @Override
    protected boolean isEntityUpdateable() {
        return true;
    }

    /**
     * Properties of entity Coordinators.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property CoordinatorsID = new Property(1, String.class, "coordinatorsID", false, "COORDINATORS_ID");
        public final static Property CoordinatorsName = new Property(2, String.class, "coordinatorsName", false, "COORDINATORS_NAME");
    }

}
