package com.mahindra.be_lms.db;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END

import android.os.Parcel;
import android.os.Parcelable;

import com.google.gson.annotations.SerializedName;

/**
 * Entity mapped to table "COORDINATORS".
 */
public class Coordinators implements Parcelable {

    public static final Creator<Coordinators> CREATOR = new Creator<Coordinators>() {
        @Override
        public Coordinators createFromParcel(Parcel source) {
            return new Coordinators(source);
        }

        @Override
        public Coordinators[] newArray(int size) {
            return new Coordinators[size];
        }
    };
    @SerializedName("none")
    private Long id;
    @SerializedName("id")
    private String coordinatorsID;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END
    @SerializedName("name")
    private String coordinatorsName;

    public Coordinators() {
    }

    public Coordinators(Long id) {
        this.id = id;
    }

    public Coordinators(Long id, String coordinatorsID, String coordinatorsName) {
        this.id = id;
        this.coordinatorsID = coordinatorsID;
        this.coordinatorsName = coordinatorsName;
    }

    protected Coordinators(Parcel in) {
        this.id = (Long) in.readValue(Long.class.getClassLoader());
        this.coordinatorsID = in.readString();
        this.coordinatorsName = in.readString();
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getCoordinatorsID() {
        return coordinatorsID;
    }

    public void setCoordinatorsID(String coordinatorsID) {
        this.coordinatorsID = coordinatorsID;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

    public String getCoordinatorsName() {
        return coordinatorsName;
    }

    public void setCoordinatorsName(String coordinatorsName) {
        this.coordinatorsName = coordinatorsName;
    }

    @Override
    public int describeContents() {
        return 0;
    }

    @Override
    public void writeToParcel(Parcel dest, int flags) {
        dest.writeValue(this.id);
        dest.writeString(this.coordinatorsID);
        dest.writeString(this.coordinatorsName);
    }
}
