package com.mahindra.be_lms.db;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END

import android.os.Parcel;
import android.os.Parcelable;

import com.google.gson.annotations.SerializedName;

/**
 * Entity mapped to table "DESIGNATION".
 */
public class Designation implements Parcelable {
    public static final Creator<Designation> CREATOR = new Creator<Designation>() {
        @Override
        public Designation createFromParcel(Parcel source) {
            return new Designation(source);
        }

        @Override
        public Designation[] newArray(int size) {
            return new Designation[size];
        }
    };
    @SerializedName("none")
    private Long id;
    @SerializedName("id")
    private String desigID;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END
    @SerializedName("name")
    private String desigName;

    public Designation() {
    }

    public Designation(Long id) {
        this.id = id;
    }

    public Designation(Long id, String desigID, String desigName) {
        this.id = id;
        this.desigID = desigID;
        this.desigName = desigName;
    }

    public Designation(String desigID, String desigName) {
        this.desigID = desigID;
        this.desigName = desigName;
    }

    protected Designation(Parcel in) {
        this.id = (Long) in.readValue(Long.class.getClassLoader());
        this.desigID = in.readString();
        this.desigName = in.readString();
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getDesigID() {
        return desigID;
    }

    public void setDesigID(String desigID) {
        this.desigID = desigID;
    }

    // KEEP METHODS - put your custom methods here

    public String getDesigName() {
        return desigName;
    }

    // KEEP METHODS END

    public void setDesigName(String desigName) {
        this.desigName = desigName;
    }

    @Override
    public String toString() {
        return desigName;
    }

    @Override
    public int describeContents() {
        return 0;
    }

    @Override
    public void writeToParcel(Parcel dest, int flags) {
        dest.writeValue(this.id);
        dest.writeString(this.desigID);
        dest.writeString(this.desigName);
    }
}
