package com.mahindra.be_lms.db;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END

import android.os.Parcel;
import android.os.Parcelable;

import com.google.gson.annotations.SerializedName;

/**
 * Entity mapped to table "DOCUMENT_TREE".
 */
public class DocumentTree implements Parcelable {
    public static final Creator<DocumentTree> CREATOR = new Creator<DocumentTree>() {
        @Override
        public DocumentTree createFromParcel(Parcel source) {
            return new DocumentTree(source);
        }

        @Override
        public DocumentTree[] newArray(int size) {
            return new DocumentTree[size];
        }
    };
    @SerializedName("none")
    private Long id;
    @SerializedName("id")
    private String documentTreeID;
    @SerializedName("item")
    private String documentTreeItem;
    @SerializedName("document")
    private String documentTreeDocument;
    @SerializedName("sequence")
    private String documentTreeSequence;
    @SerializedName("product_id")
    private String productID;
    @SerializedName("model_id")
    private String modelID;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END
    @SerializedName("parent_item")
    private String parentID;

    public DocumentTree() {
    }

    public DocumentTree(Long id) {
        this.id = id;
    }

    public DocumentTree(Long id, String documentTreeID, String documentTreeItem, String documentTreeDocument, String documentTreeSequence, String productID, String modelID, String parentID) {
        this.id = id;
        this.documentTreeID = documentTreeID;
        this.documentTreeItem = documentTreeItem;
        this.documentTreeDocument = documentTreeDocument;
        this.documentTreeSequence = documentTreeSequence;
        this.productID = productID;
        this.modelID = modelID;
        this.parentID = parentID;
    }

    protected DocumentTree(Parcel in) {
        this.id = (Long) in.readValue(Long.class.getClassLoader());
        this.documentTreeID = in.readString();
        this.documentTreeItem = in.readString();
        this.documentTreeDocument = in.readString();
        this.documentTreeSequence = in.readString();
        this.productID = in.readString();
        this.modelID = in.readString();
        this.parentID = in.readString();
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getDocumentTreeID() {
        return documentTreeID;
    }

    public void setDocumentTreeID(String documentTreeID) {
        this.documentTreeID = documentTreeID;
    }

    public String getDocumentTreeItem() {
        return documentTreeItem;
    }

    public void setDocumentTreeItem(String documentTreeItem) {
        this.documentTreeItem = documentTreeItem;
    }

    public String getDocumentTreeDocument() {
        return documentTreeDocument;
    }

    public void setDocumentTreeDocument(String documentTreeDocument) {
        this.documentTreeDocument = documentTreeDocument;
    }

    public String getDocumentTreeSequence() {
        return documentTreeSequence;
    }

    public void setDocumentTreeSequence(String documentTreeSequence) {
        this.documentTreeSequence = documentTreeSequence;
    }

    public String getProductID() {
        return productID;
    }

    public void setProductID(String productID) {
        this.productID = productID;
    }

    public String getModelID() {
        return modelID;
    }

    public void setModelID(String modelID) {
        this.modelID = modelID;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

    public String getParentID() {
        return parentID;
    }

    public void setParentID(String parentID) {
        this.parentID = parentID;
    }

    @Override
    public int describeContents() {
        return 0;
    }

    @Override
    public void writeToParcel(Parcel dest, int flags) {
        dest.writeValue(this.id);
        dest.writeString(this.documentTreeID);
        dest.writeString(this.documentTreeItem);
        dest.writeString(this.documentTreeDocument);
        dest.writeString(this.documentTreeSequence);
        dest.writeString(this.productID);
        dest.writeString(this.modelID);
        dest.writeString(this.parentID);
    }

    @Override
    public String toString() {
        return "DocumentTree{" +
                "id=" + id +
                ", documentTreeID='" + documentTreeID + '\'' +
                ", documentTreeItem='" + documentTreeItem + '\'' +
                ", documentTreeDocument='" + documentTreeDocument + '\'' +
                ", documentTreeSequence='" + documentTreeSequence + '\'' +
                ", productID='" + productID + '\'' +
                ", modelID='" + modelID + '\'' +
                ", parentID='" + parentID + '\'' +
                '}';
    }
}
