package com.mahindra.be_lms.db;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END

import android.os.Parcel;
import android.os.Parcelable;

import com.google.gson.annotations.SerializedName;

/**
 * Entity mapped to table "LOCATION".
 */
public class Location implements Parcelable {
    public static final Creator<Location> CREATOR = new Creator<Location>() {
        @Override
        public Location createFromParcel(Parcel source) {
            return new Location(source);
        }

        @Override
        public Location[] newArray(int size) {
            return new Location[size];
        }
    };
    @SerializedName("none")
    private Long id;
    @SerializedName("id")
    private String locationID;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END
    @SerializedName("name")
    private String locationName;

    public Location() {
    }

    public Location(Long id) {
        this.id = id;
    }

    public Location(Long id, String locationID, String locationName) {
        this.id = id;
        this.locationID = locationID;
        this.locationName = locationName;
    }

    public Location(String locationID, String locationName) {
        this.locationID = locationID;
        this.locationName = locationName;
    }

    protected Location(Parcel in) {
        this.id = (Long) in.readValue(Long.class.getClassLoader());
        this.locationID = in.readString();
        this.locationName = in.readString();
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getLocationID() {
        return locationID;
    }

    public void setLocationID(String locationID) {
        this.locationID = locationID;
    }

    // KEEP METHODS - put your custom methods here

    public String getLocationName() {
        return locationName;
    }
// KEEP METHODS END

    public void setLocationName(String locationName) {
        this.locationName = locationName;
    }

    @Override
    public String toString() {
        return locationName;
    }

    @Override
    public int describeContents() {
        return 0;
    }

    @Override
    public void writeToParcel(Parcel dest, int flags) {
        dest.writeValue(this.id);
        dest.writeString(this.locationID);
        dest.writeString(this.locationName);
    }
}
