package com.mahindra.be_lms.db;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END

import com.google.gson.annotations.SerializedName;

/**
 * Entity mapped to table "MENU_RIGHTS".
 */
public class MenuRights {
    @SerializedName("none")
    private Long id;
    @SerializedName("registration")
    private String registration;
    @SerializedName("search")
    private String search;
    @SerializedName("powerolCare")
    private String powerolCare;
    @SerializedName("mostViewed")
    private String mostViewed;
    @SerializedName("myProfile")
    private String myProfile;
    @SerializedName("surveyFeedbacks")
    private String surveyFeedbacks;
    @SerializedName("myTrainingPassport")
    private String myTrainingPassport;
    @SerializedName("learningTestQuizs")
    private String learningTestQuizs;
    @SerializedName("manualsBulletins")
    private String manualsBulletins;
    @SerializedName("trainingCalenderNomination")
    private String trainingCalenderNomination;
    @SerializedName("queriesResponse")
    private String queriesResponse;
    @SerializedName("technicalUploads")
    private String technicalUploads;
    @SerializedName("myFieldRecords")
    private String myFieldRecords;
    @SerializedName("reports")
    private String reports;
    @SerializedName("manpowerEdition")
    private String manpowerEdition;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public MenuRights() {
    }

    public MenuRights(Long id) {
        this.id = id;
    }

    public MenuRights(Long id, String registration, String search, String powerolCare, String mostViewed, String myProfile, String surveyFeedbacks, String myTrainingPassport, String learningTestQuizs, String manualsBulletins, String trainingCalenderNomination, String queriesResponse, String technicalUploads, String myFieldRecords, String reports, String manpowerEdition) {
        this.id = id;
        this.registration = registration;
        this.search = search;
        this.powerolCare = powerolCare;
        this.mostViewed = mostViewed;
        this.myProfile = myProfile;
        this.surveyFeedbacks = surveyFeedbacks;
        this.myTrainingPassport = myTrainingPassport;
        this.learningTestQuizs = learningTestQuizs;
        this.manualsBulletins = manualsBulletins;
        this.trainingCalenderNomination = trainingCalenderNomination;
        this.queriesResponse = queriesResponse;
        this.technicalUploads = technicalUploads;
        this.myFieldRecords = myFieldRecords;
        this.reports = reports;
        this.manpowerEdition = manpowerEdition;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getRegistration() {
        return registration;
    }

    public void setRegistration(String registration) {
        this.registration = registration;
    }

    public String getSearch() {
        return search;
    }

    public void setSearch(String search) {
        this.search = search;
    }

    public String getPowerolCare() {
        return powerolCare;
    }

    public void setPowerolCare(String powerolCare) {
        this.powerolCare = powerolCare;
    }

    public String getMostViewed() {
        return mostViewed;
    }

    public void setMostViewed(String mostViewed) {
        this.mostViewed = mostViewed;
    }

    public String getMyProfile() {
        return myProfile;
    }

    public void setMyProfile(String myProfile) {
        this.myProfile = myProfile;
    }

    public String getSurveyFeedbacks() {
        return surveyFeedbacks;
    }

    public void setSurveyFeedbacks(String surveyFeedbacks) {
        this.surveyFeedbacks = surveyFeedbacks;
    }

    public String getMyTrainingPassport() {
        return myTrainingPassport;
    }

    public void setMyTrainingPassport(String myTrainingPassport) {
        this.myTrainingPassport = myTrainingPassport;
    }

    public String getLearningTestQuizs() {
        return learningTestQuizs;
    }

    public void setLearningTestQuizs(String learningTestQuizs) {
        this.learningTestQuizs = learningTestQuizs;
    }

    public String getManualsBulletins() {
        return manualsBulletins;
    }

    public void setManualsBulletins(String manualsBulletins) {
        this.manualsBulletins = manualsBulletins;
    }

    public String getTrainingCalenderNomination() {
        return trainingCalenderNomination;
    }

    public void setTrainingCalenderNomination(String trainingCalenderNomination) {
        this.trainingCalenderNomination = trainingCalenderNomination;
    }

    public String getQueriesResponse() {
        return queriesResponse;
    }

    public void setQueriesResponse(String queriesResponse) {
        this.queriesResponse = queriesResponse;
    }

    public String getTechnicalUploads() {
        return technicalUploads;
    }

    public void setTechnicalUploads(String technicalUploads) {
        this.technicalUploads = technicalUploads;
    }

    public String getMyFieldRecords() {
        return myFieldRecords;
    }

    public void setMyFieldRecords(String myFieldRecords) {
        this.myFieldRecords = myFieldRecords;
    }

    public String getReports() {
        return reports;
    }

    public void setReports(String reports) {
        this.reports = reports;
    }

    public String getManpowerEdition() {
        return manpowerEdition;
    }

    public void setManpowerEdition(String manpowerEdition) {
        this.manpowerEdition = manpowerEdition;
    }

    // KEEP METHODS - put your custom methods here

    @Override
    public String toString() {
        return "MenuRights{" +
                "id=" + id +
                ", registration='" + registration + '\'' +
                ", search='" + search + '\'' +
                ", powerolCare='" + powerolCare + '\'' +
                ", mostViewed='" + mostViewed + '\'' +
                ", myProfile='" + myProfile + '\'' +
                ", surveyFeedbacks='" + surveyFeedbacks + '\'' +
                ", myTrainingPassport='" + myTrainingPassport + '\'' +
                ", learningTestQuizs='" + learningTestQuizs + '\'' +
                ", manualsBulletins='" + manualsBulletins + '\'' +
                ", trainingCalenderNomination='" + trainingCalenderNomination + '\'' +
                ", queriesResponse='" + queriesResponse + '\'' +
                ", technicalUploads='" + technicalUploads + '\'' +
                ", myFieldRecords='" + myFieldRecords + '\'' +
                ", reports='" + reports + '\'' +
                ", manpowerEdition='" + manpowerEdition + '\'' +
                '}';
    }
    // KEEP METHODS END

}
