package com.mahindra.be_lms.db;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END

import android.os.Parcel;
import android.os.Parcelable;

import com.google.gson.annotations.SerializedName;

/**
 * Entity mapped to table "MODEL".
 */
public class Model implements Parcelable {
    public static final Creator<Model> CREATOR = new Creator<Model>() {
        @Override
        public Model createFromParcel(Parcel source) {
            return new Model(source);
        }

        @Override
        public Model[] newArray(int size) {
            return new Model[size];
        }
    };
    @SerializedName("none")
    private Long id;
    @SerializedName("id")
    private String modelID;
    @SerializedName("model")
    private String modelName;
    @SerializedName("sequence")
    private String modelSequence;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END
    @SerializedName("product_id")
    private String productID;

    public Model() {
    }

    public Model(Long id) {
        this.id = id;
    }

    public Model(String modelID, String modelName, String modelSequence, String productID) {
        this.modelID = modelID;
        this.modelName = modelName;
        this.modelSequence = modelSequence;
        this.productID = productID;
    }

    public Model(Long id, String modelID, String modelName, String modelSequence, String productID) {
        this.id = id;
        this.modelID = modelID;
        this.modelName = modelName;
        this.modelSequence = modelSequence;
        this.productID = productID;
    }

    protected Model(Parcel in) {
        this.id = (Long) in.readValue(Long.class.getClassLoader());
        this.modelID = in.readString();
        this.modelName = in.readString();
        this.modelSequence = in.readString();
        this.productID = in.readString();
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getModelID() {
        return modelID;
    }

    public void setModelID(String modelID) {
        this.modelID = modelID;
    }

    public String getModelName() {
        return modelName;
    }

    public void setModelName(String modelName) {
        this.modelName = modelName;
    }

    public String getModelSequence() {
        return modelSequence;
    }

    public void setModelSequence(String modelSequence) {
        this.modelSequence = modelSequence;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

    public String getProductID() {
        return productID;
    }

    public void setProductID(String productID) {
        this.productID = productID;
    }

    @Override
    public int describeContents() {
        return 0;
    }

    @Override
    public void writeToParcel(Parcel dest, int flags) {
        dest.writeValue(this.id);
        dest.writeString(this.modelID);
        dest.writeString(this.modelName);
        dest.writeString(this.modelSequence);
        dest.writeString(this.productID);
    }

    @Override
    public String toString() {
        return modelName;
    }
}
