package com.mahindra.be_lms.db;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END

import android.os.Parcel;
import android.os.Parcelable;

import com.google.gson.annotations.SerializedName;

/**
 * Entity mapped to table "NOTIFICATIONS".
 */
public class Notifications implements Parcelable {

    public static final Creator<Notifications> CREATOR = new Creator<Notifications>() {
        @Override
        public Notifications createFromParcel(Parcel source) {
            return new Notifications(source);
        }

        @Override
        public Notifications[] newArray(int size) {
            return new Notifications[size];
        }
    };
    @SerializedName("none")
    private Long id;
    @SerializedName("noneid")
    private String notificationID;
    @SerializedName("title")
    private String notificationTitle;
    @SerializedName("message")
    private String notificationMsg;
    @SerializedName("type")
    private String notificationType;
    @SerializedName("notificationType")
    private String notificationOtherType;
    @SerializedName("attachmentLink")
    private String notificationattachLink;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END
    @SerializedName("extra_link")
    private String notificationextraLink;

    public Notifications() {
    }

    public Notifications(Long id) {
        this.id = id;
    }

    public Notifications(Long id, String notificationID, String notificationTitle, String notificationMsg, String notificationType, String notificationOtherType, String notificationattachLink, String notificationextraLink) {
        this.id = id;
        this.notificationID = notificationID;
        this.notificationTitle = notificationTitle;
        this.notificationMsg = notificationMsg;
        this.notificationType = notificationType;
        this.notificationOtherType = notificationOtherType;
        this.notificationattachLink = notificationattachLink;
        this.notificationextraLink = notificationextraLink;
    }

    protected Notifications(Parcel in) {
        this.id = (Long) in.readValue(Long.class.getClassLoader());
        this.notificationID = in.readString();
        this.notificationTitle = in.readString();
        this.notificationMsg = in.readString();
        this.notificationType = in.readString();
        this.notificationOtherType = in.readString();
        this.notificationattachLink = in.readString();
        this.notificationextraLink = in.readString();
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getNotificationID() {
        return notificationID;
    }

    public void setNotificationID(String notificationID) {
        this.notificationID = notificationID;
    }

    public String getNotificationTitle() {
        return notificationTitle;
    }

    public void setNotificationTitle(String notificationTitle) {
        this.notificationTitle = notificationTitle;
    }

    public String getNotificationMsg() {
        return notificationMsg;
    }

    public void setNotificationMsg(String notificationMsg) {
        this.notificationMsg = notificationMsg;
    }

    public String getNotificationType() {
        return notificationType;
    }

    public void setNotificationType(String notificationType) {
        this.notificationType = notificationType;
    }

    public String getNotificationOtherType() {
        return notificationOtherType;
    }

    public void setNotificationOtherType(String notificationOtherType) {
        this.notificationOtherType = notificationOtherType;
    }

    public String getNotificationattachLink() {
        return notificationattachLink;
    }

    public void setNotificationattachLink(String notificationattachLink) {
        this.notificationattachLink = notificationattachLink;
    }

    // KEEP METHODS - put your custom methods here

    public String getNotificationextraLink() {
        return notificationextraLink;
    }
    // KEEP METHODS END

    public void setNotificationextraLink(String notificationextraLink) {
        this.notificationextraLink = notificationextraLink;
    }

    @Override
    public String toString() {
        return "Notifications{" +
                "id=" + id +
                ", notificationID='" + notificationID + '\'' +
                ", notificationTitle='" + notificationTitle + '\'' +
                ", notificationMsg='" + notificationMsg + '\'' +
                ", notificationType='" + notificationType + '\'' +
                ", notificationOtherType='" + notificationOtherType + '\'' +
                ", notificationattachLink='" + notificationattachLink + '\'' +
                ", notificationextraLink='" + notificationextraLink + '\'' +
                '}';
    }

    @Override
    public int describeContents() {
        return 0;
    }

    @Override
    public void writeToParcel(Parcel dest, int flags) {
        dest.writeValue(this.id);
        dest.writeString(this.notificationID);
        dest.writeString(this.notificationTitle);
        dest.writeString(this.notificationMsg);
        dest.writeString(this.notificationType);
        dest.writeString(this.notificationOtherType);
        dest.writeString(this.notificationattachLink);
        dest.writeString(this.notificationextraLink);
    }
}
