package com.mahindra.be_lms.db;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END

import android.os.Parcel;
import android.os.Parcelable;

import com.google.gson.annotations.SerializedName;

/**
 * Entity mapped to table "PRODUCT".
 */
public class Product implements Parcelable {

    public static final Creator<Product> CREATOR = new Creator<Product>() {
        @Override
        public Product createFromParcel(Parcel source) {
            return new Product(source);
        }

        @Override
        public Product[] newArray(int size) {
            return new Product[size];
        }
    };
    @SerializedName("none")
    private Long id;
    @SerializedName("id")
    private String productID;
    @SerializedName("name")
    private String productName;
    @SerializedName("sequence")
    private String productSequence;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END
    @SerializedName("url")
    private String productImageUrl;

    public Product() {
    }

    public Product(Long id) {
        this.id = id;
    }

    public Product(Long id, String productID, String productName, String productSequence, String productImageUrl) {
        this.id = id;
        this.productID = productID;
        this.productName = productName;
        this.productSequence = productSequence;
        this.productImageUrl = productImageUrl;
    }

    protected Product(Parcel in) {
        this.id = (Long) in.readValue(Long.class.getClassLoader());
        this.productID = in.readString();
        this.productName = in.readString();
        this.productSequence = in.readString();
        this.productImageUrl = in.readString();
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getProductID() {
        return productID;
    }

    public void setProductID(String productID) {
        this.productID = productID;
    }

    public String getProductName() {
        return productName;
    }

    public void setProductName(String productName) {
        this.productName = productName;
    }

    public String getProductSequence() {
        return productSequence;
    }

    public void setProductSequence(String productSequence) {
        this.productSequence = productSequence;
    }

    // KEEP METHODS - put your custom methods here

    public String getProductImageUrl() {
        return productImageUrl;
    }
    // KEEP METHODS END

    public void setProductImageUrl(String productImageUrl) {
        this.productImageUrl = productImageUrl;
    }

    @Override
    public String toString() {
        return "Product{" +
                "id=" + id +
                ", productID='" + productID + '\'' +
                ", productName='" + productName + '\'' +
                ", productSequence='" + productSequence + '\'' +
                ", productImageUrl='" + productImageUrl + '\'' +
                '}';
    }

    @Override
    public int describeContents() {
        return 0;
    }

    @Override
    public void writeToParcel(Parcel dest, int flags) {
        dest.writeValue(this.id);
        dest.writeString(this.productID);
        dest.writeString(this.productName);
        dest.writeString(this.productSequence);
        dest.writeString(this.productImageUrl);
    }
}
