package com.mahindra.be_lms.db;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END

import com.google.gson.annotations.SerializedName;

/**
 * Entity mapped to table "PROFILE".
 */
public class Profile {

    @SerializedName("none")
    private Long id;
    @SerializedName("id")
    private String profileID;
    @SerializedName("name")
    private String profileName;
    @SerializedName("none1")
    private String profile_json;
    @SerializedName("none2")
    private Boolean profile_approval;
    @SerializedName("none3")
    private Boolean profile_requested;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public Profile() {
    }

    public Profile(Long id) {
        this.id = id;
    }

    public Profile(Long id, String profileID, String profileName, String profile_json, Boolean profile_approval, Boolean profile_requested) {
        this.id = id;
        this.profileID = profileID;
        this.profileName = profileName;
        this.profile_json = profile_json;
        this.profile_approval = profile_approval;
        this.profile_requested = profile_requested;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getProfileID() {
        return profileID;
    }

    public void setProfileID(String profileID) {
        this.profileID = profileID;
    }

    public String getProfileName() {
        return profileName;
    }

    public void setProfileName(String profileName) {
        this.profileName = profileName;
    }

    public String getProfile_json() {
        return profile_json;
    }

    public void setProfile_json(String profile_json) {
        this.profile_json = profile_json;
    }

    public Boolean getProfile_approval() {
        return profile_approval;
    }

    public void setProfile_approval(Boolean profile_approval) {
        this.profile_approval = profile_approval;
    }

    public Boolean getProfile_requested() {
        return profile_requested;
    }

    public void setProfile_requested(Boolean profile_requested) {
        this.profile_requested = profile_requested;
    }

    // KEEP METHODS - put your custom methods here

    @Override
    public String toString() {
        return "Profile{" +
                "id=" + id +
                ", profileID='" + profileID + '\'' +
                ", profileName='" + profileName + '\'' +
                ", profile_json='" + profile_json + '\'' +
                ", profile_approval=" + profile_approval +
                ", profile_requested=" + profile_requested +
                '}';
    }
    // KEEP METHODS END

}
