package com.mahindra.be_lms.db;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END

/**
 * Entity mapped to table "QUERY_RESPONSE".
 */
public class QueryResponse {

    private Long id;
    private String queryID;
    private String resposePerson;
    private String message;
    private String title;
    private String msg_type;
    private String queryReplyAttachment;
    private String queryResponseExtraLink;
    private String queryResponseType;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public QueryResponse() {
    }

    public QueryResponse(Long id) {
        this.id = id;
    }

    public QueryResponse(Long id, String queryID, String resposePerson, String message, String title, String msg_type, String queryReplyAttachment, String queryResponseExtraLink, String queryResponseType) {
        this.id = id;
        this.queryID = queryID;
        this.resposePerson = resposePerson;
        this.message = message;
        this.title = title;
        this.msg_type = msg_type;
        this.queryReplyAttachment = queryReplyAttachment;
        this.queryResponseExtraLink = queryResponseExtraLink;
        this.queryResponseType = queryResponseType;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getQueryID() {
        return queryID;
    }

    public void setQueryID(String queryID) {
        this.queryID = queryID;
    }

    public String getResposePerson() {
        return resposePerson;
    }

    public void setResposePerson(String resposePerson) {
        this.resposePerson = resposePerson;
    }

    public String getMessage() {
        return message;
    }

    public void setMessage(String message) {
        this.message = message;
    }

    public String getTitle() {
        return title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    public String getMsg_type() {
        return msg_type;
    }

    public void setMsg_type(String msg_type) {
        this.msg_type = msg_type;
    }

    public String getQueryReplyAttachment() {
        return queryReplyAttachment;
    }

    public void setQueryReplyAttachment(String queryReplyAttachment) {
        this.queryReplyAttachment = queryReplyAttachment;
    }

    public String getQueryResponseExtraLink() {
        return queryResponseExtraLink;
    }

    public void setQueryResponseExtraLink(String queryResponseExtraLink) {
        this.queryResponseExtraLink = queryResponseExtraLink;
    }

    public String getQueryResponseType() {
        return queryResponseType;
    }

    public void setQueryResponseType(String queryResponseType) {
        this.queryResponseType = queryResponseType;
    }

    // KEEP METHODS - put your custom methods here
    @Override
    public String toString() {
        return "QueryResponse{" +
                "id=" + id +
                ", queryID='" + queryID + '\'' +
                ", resposePerson='" + resposePerson + '\'' +
                ", message='" + message + '\'' +
                ", title='" + title + '\'' +
                ", msg_type='" + msg_type + '\'' +
                ", queryReplyAttachment='" + queryReplyAttachment + '\'' +
                ", queryResponseExtraLink='" + queryResponseExtraLink + '\'' +
                ", queryResponseType='" + queryResponseType + '\'' +
                '}';
    }
    // KEEP METHODS END
}
