package com.mahindra.be_lms.db;

import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.DaoConfig;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * DAO for table "QUERIES".
 */
public class QueriesDao extends AbstractDao<Queries, Long> {

    public static final String TABLENAME = "QUERIES";

    public QueriesDao(DaoConfig config) {
        super(config);
    }


    public QueriesDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /**
     * Creates the underlying database table.
     */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists ? "IF NOT EXISTS " : "";
        db.execSQL("CREATE TABLE " + constraint + "\"QUERIES\" (" + //
                "\"_id\" INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: id
                "\"QUERY_INSERTED_ID\" TEXT," + // 1: queryInsertedID
                "\"PRODUCT_ID\" TEXT," + // 2: productID
                "\"QUERY_SUBJECT\" TEXT," + // 3: querySubject
                "\"QUERY_BODY\" TEXT," + // 4: queryBody
                "\"QUERY_ATTACHMENT\" TEXT," + // 5: queryAttachment
                "\"QUERY_STATUS\" INTEGER);"); // 6: queryStatus
    }

    /**
     * Drops the underlying database table.
     */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"QUERIES\"";
        db.execSQL(sql);
    }

    /**
     * @inheritdoc
     */
    @Override
    protected void bindValues(SQLiteStatement stmt, Queries entity) {
        stmt.clearBindings();

        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }

        String queryInsertedID = entity.getQueryInsertedID();
        if (queryInsertedID != null) {
            stmt.bindString(2, queryInsertedID);
        }

        String productID = entity.getProductID();
        if (productID != null) {
            stmt.bindString(3, productID);
        }

        String querySubject = entity.getQuerySubject();
        if (querySubject != null) {
            stmt.bindString(4, querySubject);
        }

        String queryBody = entity.getQueryBody();
        if (queryBody != null) {
            stmt.bindString(5, queryBody);
        }

        String queryAttachment = entity.getQueryAttachment();
        if (queryAttachment != null) {
            stmt.bindString(6, queryAttachment);
        }

        Boolean queryStatus = entity.getQueryStatus();
        if (queryStatus != null) {
            stmt.bindLong(7, queryStatus ? 1L : 0L);
        }
    }

    /**
     * @inheritdoc
     */
    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }

    /**
     * @inheritdoc
     */
    @Override
    public Queries readEntity(Cursor cursor, int offset) {
        Queries entity = new Queries( //
                cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
                cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // queryInsertedID
                cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // productID
                cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3), // querySubject
                cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4), // queryBody
                cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5), // queryAttachment
                cursor.isNull(offset + 6) ? null : cursor.getShort(offset + 6) != 0 // queryStatus
        );
        return entity;
    }

    /**
     * @inheritdoc
     */
    @Override
    public void readEntity(Cursor cursor, Queries entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setQueryInsertedID(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setProductID(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setQuerySubject(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
        entity.setQueryBody(cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4));
        entity.setQueryAttachment(cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5));
        entity.setQueryStatus(cursor.isNull(offset + 6) ? null : cursor.getShort(offset + 6) != 0);
    }

    /**
     * @inheritdoc
     */
    @Override
    protected Long updateKeyAfterInsert(Queries entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }

    /**
     * @inheritdoc
     */
    @Override
    public Long getKey(Queries entity) {
        if (entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    /**
     * @inheritdoc
     */
    @Override
    protected boolean isEntityUpdateable() {
        return true;
    }

    /**
     * Properties of entity Queries.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property QueryInsertedID = new Property(1, String.class, "queryInsertedID", false, "QUERY_INSERTED_ID");
        public final static Property ProductID = new Property(2, String.class, "productID", false, "PRODUCT_ID");
        public final static Property QuerySubject = new Property(3, String.class, "querySubject", false, "QUERY_SUBJECT");
        public final static Property QueryBody = new Property(4, String.class, "queryBody", false, "QUERY_BODY");
        public final static Property QueryAttachment = new Property(5, String.class, "queryAttachment", false, "QUERY_ATTACHMENT");
        public final static Property QueryStatus = new Property(6, Boolean.class, "queryStatus", false, "QUERY_STATUS");
    }

}
