package com.mahindra.be_lms.db;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END

import android.os.Parcel;
import android.os.Parcelable;

/**
 * Entity mapped to table "QUERIES".
 */
public class Queries implements Parcelable {

    public static final Creator<Queries> CREATOR = new Creator<Queries>() {
        @Override
        public Queries createFromParcel(Parcel source) {
            return new Queries(source);
        }

        @Override
        public Queries[] newArray(int size) {
            return new Queries[size];
        }
    };
    private Long id;
    private String queryInsertedID;
    private String productID;
    private String querySubject;
    private String queryBody;
    private String queryAttachment;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END
    private Boolean queryStatus;

    public Queries() {
    }

    public Queries(Long id) {
        this.id = id;
    }

    public Queries(Long id, String queryInsertedID, String productID, String querySubject, String queryBody, String queryAttachment, Boolean queryStatus) {
        this.id = id;
        this.queryInsertedID = queryInsertedID;
        this.productID = productID;
        this.querySubject = querySubject;
        this.queryBody = queryBody;
        this.queryAttachment = queryAttachment;
        this.queryStatus = queryStatus;
    }

    protected Queries(Parcel in) {
        this.id = (Long) in.readValue(Long.class.getClassLoader());
        this.queryInsertedID = in.readString();
        this.productID = in.readString();
        this.querySubject = in.readString();
        this.queryBody = in.readString();
        this.queryAttachment = in.readString();
        this.queryStatus = (Boolean) in.readValue(Boolean.class.getClassLoader());
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getQueryInsertedID() {
        return queryInsertedID;
    }

    public void setQueryInsertedID(String queryInsertedID) {
        this.queryInsertedID = queryInsertedID;
    }

    public String getProductID() {
        return productID;
    }

    public void setProductID(String productID) {
        this.productID = productID;
    }

    public String getQuerySubject() {
        return querySubject;
    }

    public void setQuerySubject(String querySubject) {
        this.querySubject = querySubject;
    }

    public String getQueryBody() {
        return queryBody;
    }

    public void setQueryBody(String queryBody) {
        this.queryBody = queryBody;
    }

    public String getQueryAttachment() {
        return queryAttachment;
    }

    public void setQueryAttachment(String queryAttachment) {
        this.queryAttachment = queryAttachment;
    }

    // KEEP METHODS - put your custom methods here

    public Boolean getQueryStatus() {
        return queryStatus;
    }

    // KEEP METHODS END

    public void setQueryStatus(Boolean queryStatus) {
        this.queryStatus = queryStatus;
    }

    @Override
    public String toString() {
        return "Queries{" +
                "id=" + id +
                ", queryInsertedID='" + queryInsertedID + '\'' +
                ", productID='" + productID + '\'' +
                ", querySubject='" + querySubject + '\'' +
                ", queryBody='" + queryBody + '\'' +
                ", queryAttachment='" + queryAttachment + '\'' +
                ", queryStatus=" + queryStatus +
                '}';
    }

    @Override
    public int describeContents() {
        return 0;
    }

    @Override
    public void writeToParcel(Parcel dest, int flags) {
        dest.writeValue(this.id);
        dest.writeString(this.queryInsertedID);
        dest.writeString(this.productID);
        dest.writeString(this.querySubject);
        dest.writeString(this.queryBody);
        dest.writeString(this.queryAttachment);
        dest.writeValue(this.queryStatus);
    }
}
