package com.mahindra.be_lms.db;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END

import android.os.Parcel;
import android.os.Parcelable;

import com.google.gson.annotations.SerializedName;

/**
 * Entity mapped to table "SUB_CATEGORY".
 */
public class SubCategory implements Parcelable {
    public static final Creator<SubCategory> CREATOR = new Creator<SubCategory>() {
        @Override
        public SubCategory createFromParcel(Parcel source) {
            return new SubCategory(source);
        }

        @Override
        public SubCategory[] newArray(int size) {
            return new SubCategory[size];
        }
    };
    @SerializedName("none")
    private Long id;
    @SerializedName("id")
    private String subCategoryID;
    @SerializedName("subcategory")
    private String subCategoryName;
    @SerializedName("sequence")
    private String subCategorySequence;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END
    @SerializedName("category_id")
    private String categoryID;

    public SubCategory() {
    }

    public SubCategory(Long id) {
        this.id = id;
    }

    public SubCategory(Long id, String subCategoryID, String subCategoryName, String subCategorySequence, String categoryID) {
        this.id = id;
        this.subCategoryID = subCategoryID;
        this.subCategoryName = subCategoryName;
        this.subCategorySequence = subCategorySequence;
        this.categoryID = categoryID;
    }

    public SubCategory(String categoryID, String subCategoryID, String subCategoryName, String subCategorySequence) {
        this.categoryID = categoryID;
        this.subCategoryID = subCategoryID;
        this.subCategoryName = subCategoryName;
        this.subCategorySequence = subCategorySequence;
    }

    protected SubCategory(Parcel in) {
        this.id = (Long) in.readValue(Long.class.getClassLoader());
        this.subCategoryID = in.readString();
        this.subCategoryName = in.readString();
        this.subCategorySequence = in.readString();
        this.categoryID = in.readString();
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getSubCategoryID() {
        return subCategoryID;
    }

    public void setSubCategoryID(String subCategoryID) {
        this.subCategoryID = subCategoryID;
    }

    public String getSubCategoryName() {
        return subCategoryName;
    }

    public void setSubCategoryName(String subCategoryName) {
        this.subCategoryName = subCategoryName;
    }

    public String getSubCategorySequence() {
        return subCategorySequence;
    }

    public void setSubCategorySequence(String subCategorySequence) {
        this.subCategorySequence = subCategorySequence;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

    public String getCategoryID() {
        return categoryID;
    }

    public void setCategoryID(String categoryID) {
        this.categoryID = categoryID;
    }

    @Override
    public int describeContents() {
        return 0;
    }

    @Override
    public void writeToParcel(Parcel dest, int flags) {
        dest.writeValue(this.id);
        dest.writeString(this.subCategoryID);
        dest.writeString(this.subCategoryName);
        dest.writeString(this.subCategorySequence);
        dest.writeString(this.categoryID);
    }

    @Override
    public String toString() {
        return subCategoryName;
    }
}
