package com.mahindra.be_lms.db;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END

import android.os.Parcel;
import android.os.Parcelable;

import com.google.gson.annotations.SerializedName;

/**
 * Entity mapped to table "TRAINERS".
 */
public class Trainers implements Parcelable {

    public static final Creator<Trainers> CREATOR = new Creator<Trainers>() {
        @Override
        public Trainers createFromParcel(Parcel source) {
            return new Trainers(source);
        }

        @Override
        public Trainers[] newArray(int size) {
            return new Trainers[size];
        }
    };
    @SerializedName("none")
    private Long id;
    @SerializedName("id")
    private String trainersID;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END
    @SerializedName("name")
    private String trainersName;

    public Trainers() {
    }

    public Trainers(Long id) {
        this.id = id;
    }

    public Trainers(Long id, String trainersID, String trainersName) {
        this.id = id;
        this.trainersID = trainersID;
        this.trainersName = trainersName;
    }

    protected Trainers(Parcel in) {
        this.id = (Long) in.readValue(Long.class.getClassLoader());
        this.trainersID = in.readString();
        this.trainersName = in.readString();
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getTrainersID() {
        return trainersID;
    }

    public void setTrainersID(String trainersID) {
        this.trainersID = trainersID;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

    public String getTrainersName() {
        return trainersName;
    }

    public void setTrainersName(String trainersName) {
        this.trainersName = trainersName;
    }

    @Override
    public int describeContents() {
        return 0;
    }

    @Override
    public void writeToParcel(Parcel dest, int flags) {
        dest.writeValue(this.id);
        dest.writeString(this.trainersID);
        dest.writeString(this.trainersName);
    }
}
